### ISSUE TITLE
Separate map items - trouble creating a navmesh

### ISSUE THREAD

**Issue by MrSonicMaster** [donmccurdy/three-pathfinding#17]
I'm trying to use this pathfinding library to allow NPC's in a ThreeJS game I'm working on to walk around from point A to point B, up and down slopes. This library sounds perfect for this, however looking at the docs it appeared to me that the only way to create a navmesh to work with this is with a single OBJ file containing all map data. Having the entire map as one obj file isn't the easiest way for me to handle separate maps in my scenario, so the way I create my ThreeJS map is with an array of objects for all the map items (crates with their own textures, walls, floors, ramps, you get the point.) My game code simply loops through this and adds them to the map, handling textures and everything as it goes.

Due to the way I'm creating/adding three.js objects to my scene, I'm finding it difficult to create a navigation mesh, and, obviously, without this I'm unable to use this library for pathfinding. I've researched all over the internet but I've been unsuccessful. How might I go about creating a navigation mesh with all my map items being separate? If anyone could point me to some links or give me some insight into how this might be accomplished, this would be appreciated.

**Comment by MrSonicMaster** [comment]
Hello Don,

Thank you for the fast response. For the most part I was aware that I was required to create a navmesh ahead of time for this library to use. My issue is my complete incompetence in 3D modeling software and how I would take my map data and import that into the software that creates the navmesh for me. My map data is an array of objects containing data such as the X, Y, and Z position, length, width, height, texture path, etc. and most 3D modeling software and the JavaScript reCast github repository you sent me don't make it look easy to turn my map data array into a navmesh. Maybe I'm incorrect, and if so feel free to correct me, but I'll be researching into recast-cli until then.

Map data example:
```
[{
x: 100,
y: 100,
z: 100,
l: 5,
w: 5,
h: 5,
t: 'crate.png',
tt: 0
}, 
{...];
```

**Comment by donmccurdy** [comment]
Not removed yet, but still deprecated along with the rest of Blender's game engine. :(

**Comment by dirkk0** [comment]
@MrSonicMaster Blender can be automated via Python. I found it not too hard to write import/export scripts that automate certain process (like shadow baking).
It could be worth thinking about taking your JSON, importing it into Blender, navmeshing it (yes, this is a verb now :-) ) and exporting it to OBJ.

**Comment by MrSonicMaster** [comment]
Everything is loaded in at once, the map isn't super large, and it's not open-world.

I'll see what I can do with exporting the scene's geometry and computing a navmesh externally.

**Comment by donmccurdy** [comment]
I reorganized some of the code in the A-Frame plugin to be a bit more reusable, if that's helpful: https://github.com/donmccurdy/aframe-inspector-plugin-recast/blob/master/src/three-geometry-reducer.js

Example:

```js
var reducer = new GeometryReducer();
scene.traverse((o) => reducer.add(o));

// Option 1: create position/index pair:
const { position, index } = reducer.reduce();

// Option 2: download glTF
reducer.reduceAndDownloadGLTF();
```

**Comment by MrSonicMaster** [comment]
That helped a lot, I've got the entire map glTF file now, but I can't built recastCLI on my operating system, and I don't seem to be the only one with this issue. That's for the recastCLI github though, not here. My issue here is solved, thank you for the help.

**Comment by MrSonicMaster** [comment]
I've used the library you sent me to compile my loaded three.js map into a single glTF file and downloaded it, and I've been successful in creating the navmesh (according to blender, as recastCLI wouldn't compile for me.) The map renders perfectly fine & to scale without textures (like it should) in blender, however for some reason the 'faces' attribute don't seem to be saving to the glTF file I downloaded, which is necessary for this pathfinding library. This yields the error:

```
TypeError: Cannot read property 'length' of undefined
```

referring to this function in your utils class:

```
static computeCentroids(geometry) {
		var f, fl, face;

		for (f = 0, fl = geometry.faces.length; f < fl; f++) { // this line here, geometry.faces isn't defined.
			face = geometry.faces[f];
			face.centroid = new THREE.Vector3(0, 0, 0);

			face.centroid.add(geometry.vertices[face.a]);
			face.centroid.add(geometry.vertices[face.b]);
			face.centroid.add(geometry.vertices[face.c]);
			face.centroid.divideScalar(3);
		}
	}
```

My complete incompetence in how three.js works, this being the first time I've used it and I'm still learning new stuff every time, yields me unable to figure out how to solve this on my own. Google was also not helpful, though maybe my search terms were off. I hate having to re-open this, but help would be welcomed (and possibly this would help others who come across a similar issue to this following a similar path that I did.)

**Comment by MrSonicMaster** [comment]
Damn, totally slipped right over my head that this needs Geometry, not BufferGeometry. For others facing anything like this, just convert your BufferGeometry to a Geometry instance like so

```
const geometry = new THREE.Geometry().fromBufferGeometry(bufferGeometry);
```

easy enough.

**Comment by donmccurdy** [comment]
Glad you could figure it out! Does the navmesh seem to be working properly then?

Also the master branch of this repository accepts `THREE.BufferGeometry`, since `THREE.Geometry` is on its way out of three.js (or at least won't be supported for rendering anymore). I just haven't published a new release with that change yet.

**Comment by MrSonicMaster** [comment]
I downloaded the master branch, and I think you forgot to build the pre-built library in the dist folder due to the 'utils.js' being renamed incorrectly. After re-naming it with a capital letter and build it myself, I was able to have it accept a BufferGeometry instance. That being said, I'm getting a stack overflow error that happens during the 'createZone' call. The code in question is in Builder.js:

```
const spreadGroupId = function(polygon) {
			polygon.neighbours.forEach(neighbour => {
				if (neighbour.group === undefined) {
					neighbour.group = polygon.group;
					spreadGroupId(neighbour);
				}
			});
		};
```

My code is as follows:

```
function createPathFinder({ geometry }, zoneName = 'Scene') {
	const pathFinder = new PathFinder();
	pathFinder.zoneName = zoneName; // Store name for later use

	const zone = PathFinder.createZone(geometry); // This causes stackoverflow at the code shown above

	// pathFinder.setZoneData(pathFinder.zoneName, zone); // Still stack overflows without this

	return pathFinder;
}
```

I'm not sure if it's an issue with my code, or if it's a bug.

**Comment by donmccurdy** [comment]
Are you getting the stack overflow only on the master branch, or when using the published version as well? Could you share the navmesh?

**Comment by MrSonicMaster** [comment]
I was getting it on published one as well.

http://206.189.203.245/navmesh.gltf
http://206.189.203.245/navmesh.bin

zone name: AuxScene

**Comment by donmccurdy** [comment]
Published a new release, and the utils/Utils issue should be fixed (for some reason it was working on my OS...). But I can't reproduce the stack overflow, testing with this code:


```js
var loader = new THREE.GLTFLoader();
loader.load( 'navmesh.gltf', ( gltf ) => {
  var navmesh = gltf.scene.getChildByName('Navmesh');
  var zoneNodes = THREE.Pathfinding.createZone(navmesh.geometry);
}, undefined, (e) => console.error(e));
```

**Comment by MrSonicMaster** [comment]
I'm still getting a stack overflow after downloading the latest master branch using the npm command `npm i donmccurdy/three-pathfinding master`

My code is

```
function createPathFinder({ geometry }, zoneName = 'AuxScene') {
	const pathFinder = new PathFinder();
	pathFinder.zoneName = zoneName;

	const zone = PathFinder.createZone(geometry);

	pathFinder.setZoneData(pathFinder.zoneName, zone);

	return pathFinder;
}

const loader = new GLTFLoader();

loader.load('./navmesh.gltf', ({ scene }) => {
	console.log('Success!');

	startPathFinder(scene.getObjectByName('Navmesh'));
});
```

I can confirm that I do indeed have the newer version and I've also tried re-building myself again to see if that helped. Weird.

It shouldn't matter much, but I might as well mention that I'm using Ubuntu 18.04.1 LTS as my main operating system.

**Comment by donmccurdy** [comment]
You shouldn't have to download from master at this point, the npm `three-pathfinding` module is up to date now. But assuming that's behaving the same way, I'm not sure what to make of that, it does seem to be behaving normally here. What version of three.js is this? I tested r96. If that doesn't help either, a live demo might be good to compare. 

Reopening.

**Comment by MrSonicMaster** [comment]
I'm using the latest published npm module of three.js (r96) with the latest release of your pathfinder library. No idea what might be causing the issue for me. If you want external contact information such as my discord account I can provide that to allow us to screenshare and whatnot.

**Comment by donmccurdy** [comment]
Sure, my email is on https://github.com/donmccurdy/, or you can DM me on Twitter or http://discourse.threejs.org/. :)
